#!/bin/bash
# Helper script to test Pineapple with MCP Inspector

set -e

echo "🔨 Building MCPExample..."
swift build

BIN_PATH=$(swift build --show-bin-path)
EXECUTABLE="$BIN_PATH/MCPExample"

echo "✅ Build complete!"
echo ""
echo "📦 Executable location:"
echo "   $EXECUTABLE"
echo ""
echo "🔍 To test with MCP Inspector, use one of these methods:"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "Method 1: Using the Web Inspector (Recommended)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "1. Open: https://inspector.mcp.run"
echo ""
echo "2. Configure with:"
echo ""
echo "   Command:"
echo "   $EXECUTABLE"
echo ""
echo "   Arguments:"
echo "   stdio"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "Method 2: Using npx (if installed)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "   npx @modelcontextprotocol/inspector \\"
echo "     $EXECUTABLE \\"
echo "     stdio"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "Method 3: Test manually with curl (HTTP mode)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "1. Start HTTP server:"
echo "   swift run MCPExample http"
echo ""
echo "2. In another terminal, test with curl:"
echo "   curl -X POST http://localhost:8080/math \\"
echo "     -H 'Content-Type: application/json' \\"
echo "     -d '{\"jsonrpc\":\"2.0\",\"method\":\"tools/list\",\"id\":1}'"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "📚 What you'll see in MCP Inspector:"
echo ""
echo "   Tools:"
echo "   • add_numbers - Adds two numbers together"
echo ""
echo "   Resources:"
echo "   • math://constants/pi - Returns π (3.14159)"
echo ""
echo "   Prompts:"
echo "   • explain_math - Explains mathematical concepts"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "🧪 Quick manual test:"
echo ""
echo "   echo '{\"jsonrpc\":\"2.0\",\"id\":\"1\",\"method\":\"tools/list\"}' | $EXECUTABLE stdio"
echo ""
