import Foundation
import Logging

// MARK: - Prompt Request Types

/// Request context for prompt handlers
///
/// Provides access to prompt arguments, path parameters (from the route), and the MCP context.
/// This enables multi-tenant prompt architectures where the same prompt can serve different
/// customers/tenants based on the route.
///
/// ## Parameter Types
///
/// - **arguments**: Prompt-specific arguments provided by the client
/// - **pathParams**: Extracted from the router URL pattern (e.g., `/mcp/{customerId}/prompts`)
/// - **context**: MCP request context with requestId, method, logger, and metadata
/// - **logger**: Request-scoped logger with request metadata
///
/// ## Example
///
/// ```swift
/// // Router pattern: /mcp/{customerId}/prompts
/// // URL: /mcp/acme-corp/prompts
/// // Arguments: {"code": "...", "language": "swift"}
///
/// server.addPrompt("code_review", arguments: [...]) { request in
///     let customerId = try request.pathParamOrThrow("customerId")     // "acme-corp"
///     let code = try request.argumentOrThrow("code")                  // code string
///     let language = request.arguments.string("language") ?? "unknown"
///
///     // Generate customer-specific review prompt
///     return PromptHandlerResponse(messages: [
///         PromptMessage(role: "system", content: .text("Review \(language) code for \(customerId)")),
///         PromptMessage(role: "user", content: .text(code))
///     ])
/// }
/// ```
public struct PromptHandlerRequest {

    /// MCP request context with requestId, method, logger, and metadata
    public let context: MCPContext

    /// Prompt-specific arguments provided by the client
    ///
    /// Contains values passed when the client invokes the prompt.
    public let arguments: Params

    /// Parameters extracted from the URL route pattern
    ///
    /// Contains values from the router path like `/mcp/{customerId}/prompts`.
    /// May be nil if no router path parameters are defined.
    public let pathParams: Params?

    /// Request-scoped logger with MCP request metadata
    ///
    /// Includes requestId and method in log metadata for request correlation.
    public let logger: Logger

    /// Get a required argument or throw an error
    ///
    /// Convenience method to safely extract prompt arguments with clear error messages.
    ///
    /// - Parameter name: The argument name
    /// - Returns: The argument value as a string
    /// - Throws: MCPError with parseError code if argument is not found
    public func argumentOrThrow(_ name: String) throws -> String {
        if let arg = arguments[name] {
            return arg
        } else {
            throw MCPError(code: MCPErrorCode.parseError, message: "Unable to parse prompt argument = \(name)")
        }
    }

    /// Get a required path parameter or throw an error
    ///
    /// Convenience method to safely extract path parameters with clear error messages.
    ///
    /// - Parameter name: The parameter name from the route pattern
    /// - Returns: The parameter value
    /// - Throws: MCPError with parseError code if parameter is not found
    public func pathParamOrThrow(_ name: String) throws -> String {
        if let pathParam = pathParams?[name] {
            return pathParam
        } else {
            throw MCPError(code: MCPErrorCode.parseError, message: "Unable to parse path parameter = \(name)")
        }
    }
}

// MARK: - Prompt Response Types

/// Response returned from prompt handlers
///
/// Encapsulates the messages generated by a prompt handler. Provides a consistent
/// return type across all prompt handlers.
///
/// ## Example
///
/// ```swift
/// return PromptHandlerResponse(messages: [
///     PromptMessage(role: "system", content: .text("You are a helpful assistant")),
///     PromptMessage(role: "user", content: .text("Hello!"))
/// ])
/// ```
public struct PromptHandlerResponse {

    /// The generated prompt messages
    public let messages: [PromptMessage]

    public init(messages: [PromptMessage]) {
        self.messages = messages
    }
}

// MARK: - Internal Prompt Types

struct DynamicKey: CodingKey {
    var stringValue: String
    var intValue: Int?

    init?(stringValue: String) {
        self.stringValue = stringValue
        self.intValue = nil
    }

    init?(intValue: Int) {
        self.stringValue = String(intValue)
        self.intValue = intValue
    }
}

struct PromptDefinition {
    let prompt: Prompt
    let handler: (PromptHandlerRequest) async throws -> PromptHandlerResponse
}

struct PromptInfo: Encodable {
    let name: String
    let description: String
    let arguments: [PromptArgumentInfo]
}

struct PromptsListResponse: Encodable {
    let prompts: [PromptInfo]
}

struct PromptArgumentInfo: Encodable {
    let name: String
    let description: String
    let required: Bool
}

public struct PromptGetResponse: Encodable {
    public let description: String
    public let messages: [PromptMessageInfo]
    
    public init(description: String, messages: [PromptMessageInfo]) {
        self.description = description
        self.messages = messages
    }
}

public struct PromptMessageInfo: Encodable {
    public let role: String
    public let content: PromptContent

    public init(role: String, content: PromptContent) {
        self.role = role
        self.content = content
    }

}

public struct Prompt: Codable {
    public let name: String
    public let description: String?
    public let arguments: [PromptArgument]?
    
    public init(name: String, description: String? = nil, arguments: [PromptArgument]? = nil) {
        self.name = name
        self.description = description
        self.arguments = arguments
    }
}

public struct PromptArgument: Codable {
    public let name: String
    public let description: String?
    public let required: Bool?
    
    public init(name: String, description: String? = nil, required: Bool? = nil) {
        self.name = name
        self.description = description
        self.required = required
    }
}

public struct PromptMessage: Codable {
    
    public enum Role: String, Codable {
        case user
        case assistant
    }
    
    public let role: Role
    public let content: PromptContent
    
    public init(role: Role, content: PromptContent) {
        self.role = role
        self.content = content
    }
}

public enum PromptContent: Codable {
    /// Plain text content
    case text(String)

    /// Image data with MIME type
    /// - Parameters:
    ///   - data: Binary image data
    ///   - mimeType: MIME type (e.g., "image/png", "image/jpeg")
    case image(Data, String)

    /// Audio data with MIME type
    /// - Parameters:
    ///   - data: Binary audio data
    ///   - mimeType: MIME type (e.g., "audio/mp3", "audio/wav")
    case audio(Data, String)

    /// Embedded resource reference
    /// - Parameter resource: Complete resource with content
    case embeddedResource(Resource)

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        let type = try container.decode(String.self, forKey: .type)

        switch type {
        case "text":
            let text = try container.decode(String.self, forKey: .text)
            self = .text(text)
        case "image":
            let dataString = try container.decode(String.self, forKey: .data)
            let mimeType = try container.decode(String.self, forKey: .mimeType)
            guard let data = Data(base64Encoded: dataString) else {
                throw DecodingError.dataCorruptedError(forKey: .data, in: container, debugDescription: "Invalid base64")
            }
            self = .image(data, mimeType)
        case "audio":
            let dataString = try container.decode(String.self, forKey: .data)
            let mimeType = try container.decode(String.self, forKey: .mimeType)
            guard let data = Data(base64Encoded: dataString) else {
                throw DecodingError.dataCorruptedError(forKey: .data, in: container, debugDescription: "Invalid base64")
            }
            self = .audio(data, mimeType)
        case "resource":
            let resource = try container.decode(Resource.self, forKey: .resource)
            self = .embeddedResource(resource)
        default:
            throw DecodingError.dataCorruptedError(forKey: .type, in: container, debugDescription: "Unknown content type")
        }
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)

        switch self {
        case .text(let text):
            try container.encode("text", forKey: .type)
            try container.encode(text, forKey: .text)
        case .image(let data, let mimeType):
            try container.encode("image", forKey: .type)
            try container.encode(data.base64EncodedString(), forKey: .data)
            try container.encode(mimeType, forKey: .mimeType)
        case .audio(let data, let mimeType):
            try container.encode("audio", forKey: .type)
            try container.encode(data.base64EncodedString(), forKey: .data)
            try container.encode(mimeType, forKey: .mimeType)
        case .embeddedResource(let resource):
            try container.encode("resource", forKey: .type)
            try container.encode(resource, forKey: .resource)
        }
    }

    private enum CodingKeys: String, CodingKey {
        case type, text, data, mimeType, resource
    }
}
